#!/usr/bin/env python3
"""Draft a units.yaml from the two live accounts.

Mapping 60 rentals to 100-odd locks by hand is exactly the sort of job where a
transposed digit produces a code on the wrong door. This reads both accounts
and writes a starter file so the only thing left to do is pair them up.

    python scripts/bootstrap_units.py > units.draft.yaml

Nothing is written to any lock and nothing is changed on either platform --
this only reads. Review the draft, delete what you do not manage, fill in the
lock ids, then save it as units.yaml.

Listing ids are taken from *actual reservations* rather than assumed from the
listings endpoint, because `listingMapId` on a reservation is the field the
bridge matches on and it is the one that has to be right.
"""

from __future__ import annotations

import asyncio
import datetime as dt
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.config import get_settings  # noqa: E402
from app.db import init_db  # noqa: E402
from app.hostaway import HostawayClient  # noqa: E402
from app.ttlock import TTLockClient  # noqa: E402


def esc(text: str) -> str:
    return str(text).replace('"', "'")


async def main() -> int:
    settings = get_settings()
    init_db(settings.database_url)

    hostaway = HostawayClient(settings)
    ttlock = TTLockClient(settings)

    try:
        listings = await hostaway.list_listings()
        today = dt.date.today()
        reservations = await hostaway.iter_reservations_in_window(
            today - dt.timedelta(days=90), today + dt.timedelta(days=365)
        )
        locks = await ttlock.list_locks()
    finally:
        await hostaway.aclose()
        await ttlock.aclose()

    names = {
        int(l["id"]): l.get("name") or l.get("internalListingName") or ""
        for l in listings
        if l.get("id") is not None
    }
    seen = Counter(
        int(r["listingMapId"])
        for r in reservations
        if r.get("listingMapId") is not None
    )

    out: list[str] = []
    w = out.append

    w("# Draft generated by scripts/bootstrap_units.py -- REVIEW BEFORE USE.")
    w("#")
    w("# Locks on the TTLock account:")
    w("#")
    w(f"#   {'lock_id':>12}  {'gateway':<8} {'batt':<5} alias")
    for lock in sorted(locks, key=lambda l: str(l.get("lockAlias") or "")):
        gw = "yes" if lock.get("hasGateway") else "NO"
        w(
            f"#   {int(lock['lockId']):>12}  {gw:<8} "
            f"{str(lock.get('electricQuantity', '?')) + '%':<5} "
            f"{esc(lock.get('lockAlias') or lock.get('lockName') or '')}"
        )
    w("#")
    w(f"# {len(locks)} lock(s) total. A door showing gateway=NO still works, but")
    w("# its code cannot be revoked early -- see the README.")
    w("")

    w("defaults:")
    w("  timezone: Europe/London        # <-- CHECK THIS")
    w('  check_in_time: "15:00"')
    w('  check_out_time: "11:00"')
    w("  buffer_before_minutes: 60")
    w("  buffer_after_minutes: 60")
    w("  code_length: 6")
    w("  strategy: auto")
    w("")
    w("units:")

    if not seen:
        w("  # No reservations found in the window, so no listing ids could be")
        w("  # confirmed from real data. Fall back to the listings endpoint:")
        for listing_id, name in sorted(names.items(), key=lambda kv: kv[1]):
            w(f'  - listing_map_id: {listing_id}   # {esc(name)} (UNCONFIRMED)')
            w("    locks: []")
        return _emit(out)

    for listing_id, count in seen.most_common():
        name = names.get(listing_id, "")
        label = esc(name) if name else "NOT FOUND in /listings -- check this"
        w(f'  - listing_map_id: {listing_id}')
        w(f'    name: "{label}"')
        w(f"    # {count} reservation(s) in the last 90 / next 365 days")
        w("    # shared_code: true          # one code for entrance + flat")
        w("    locks:")
        w("      # - lock_id: 0             # copy from the table above")
        w('      #   label: "Front door"')
        w("      #   primary: true          # this code goes to the guest")
    w("")
    w(f"# {len(seen)} listing(s) have real reservations.")
    unused = sorted(set(names) - set(seen))
    if unused:
        w(f"# {len(unused)} listing(s) had no reservations in the window:")
        for listing_id in unused:
            w(f"#   {listing_id}  {esc(names[listing_id])}")
    return _emit(out)


def _emit(lines: list[str]) -> int:
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
